
name: Generate Forecast and Deploy

on:
  push:
    branches: [main]
  schedule:
    - cron: '10 2 * * *'  # every day at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirement.txt

      - name: Run forecast script
        run: python HI.py

      - name: Commit and push updated image
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add image/*.png
          git diff --cached --quiet || git commit -m "Update forecast image"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
